using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class MenuControl : MonoBehaviour {

	public GameObject creditCard;
	public GameObject optionCard;
	public GameObject playButton;
	public GameObject optionButton;
	public GameObject exitButton;


	// Use this for initialization
	void Start () {
		
	}
	
	// Update is called once per frame
	void Update () {
		
	}
}
